version: '3'
services:
  pawpaw-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pawpaw-backend
    command: npm run start:dev
    env_file:
      - ./.env.development
    ports:
      - '3000:3000'
    depends_on:
      - pawpaw-prometheus
    networks:
      - monitoring
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  pawpaw-prometheus:
    image: prom/prometheus:latest
    container_name: pawpaw-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    networks:
      - monitoring
    depends_on:
      - redis-exporter

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - monitoring

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis-exporter
    environment:
      REDIS_ADDR: redis:6379
    ports:
      - '9121:9121'
    networks:
      - monitoring
    depends_on:
      - redis


networks:
  monitoring:
    driver: bridge